### ISSUE TITLE
Cannot Import riskparityportfolio in Jupyter Notebook or Lab: Undefined Symbol error 

### ISSUE THREAD

**Issue by Sp3ctro** [convexfi/riskparity.py#14] opened 2021-11-22 16:14 UTC
#### Problem description
Hi! I'm getting the following error when importing riskparityportfolio in Jupyter Notebooks or in Jupyter Lab. 

> ImportError: /home/<username>/riskparity.py/riskparityportfolio/vanilla.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

![Screenshot from 2021-11-22 17-13-45](https://user-images.githubusercontent.com/24855562/142896313-f53a00c5-1376-4a86-bfce-8b11186205e2.png)

#### Example

```python
import riskparityportfolio as rp
```
or 
```python
from riskparityportfolio import vanilla
```
...as was advised in another issue. 
#### Expected behavior
I would expect riskparityportfolios to work in jupyter notebooks and in lab as it has done before. Oddly I have found in the past that if I make import riskparityportfolio as rp the first line in the notebook, it works. But this is no longer reliable (seems to no longer work). Using it in a script works fine. 

#### Environment:
- platform (e.g. Linux, OSX, Windows): Ubuntu 21.10
- riskparityportfolio version (e.g. 1.1): riskparityportfolio 0.2
- Python: Conda Python 3.9
- installation method (e.g. pip, source): pip and the dev version via git clone (as advised in another issue)
- Jupyter versions:
-  jupyter-client                7.0.6
- jupyter-core                  4.8.1
- jupyter-server                1.11.2
- jupyterlab                    3.2.1
- jupyterlab-pygments           0.1.2
- jupyterlab-server             2.8.2

Thanks in advance for taking a look!

**Comment by mirca** [comment] 2022-10-10 06:48
I'm closing this as I cannot reproduce the error.  Please feel free to reopen in case you still face this issue.

**Closed as completed by mirca** 2022-10-10 06:48 UTC
